# Generated by Django 6.0.5 on 2026-05-09 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_types', to='dashboard.producttype')),
            ],
            options={
                'unique_together': {('name', 'product_type')},
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('total_new', models.PositiveIntegerField(default=0)),
                ('total_used', models.PositiveIntegerField(default=0)),
                ('size_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shelf_number', models.PositiveIntegerField()),
                ('column_number', models.PositiveIntegerField()),
                ('row_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='dashboard.brand')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='dashboard.parttype')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='dashboard.producttype')),
            ],
            options={
                'unique_together': {('product_type', 'brand', 'part_type'), ('shelf_number', 'column_number', 'row_number')},
            },
        ),
    ]
